import { config } from 'dotenv';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

config();

const apiNinjasKey = process.env.API_NINJAS_KEY || 'your_api_key_here';

const envContent = `// This file is auto-generated by scripts/generate-env.js
// DO NOT EDIT MANUALLY - changes will be overwritten

export const environment = {
  production: false,
  apiNinjasKey: '${apiNinjasKey}'
};
`;

const outputPath = join(__dirname, '..', 'src', 'environments', 'environment.ts');

try {
  mkdirSync(dirname(outputPath), { recursive: true });
} catch (e) {
  // Directory already exists
}

writeFileSync(outputPath, envContent);
console.log('Generated src/environments/environment.ts');
